services:
  postgres:
    image: postgres:15-alpine
    container_name: interview_prep_db
    restart: always
    environment:
      POSTGRES_USER: interview_user
      POSTGRES_PASSWORD: interview_pass
      POSTGRES_DB: interview_prep
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U interview_user -d interview_prep"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: interview_prep_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://interview_user:interview_pass@postgres:5432/interview_prep?sslmode=disable
      PORT: 8080
      NODE_ENV: production
    depends_on:
      postgres:
        condition: service_healthy
    command: ./main

volumes:
  postgres_data: 